### ISSUE TITLE
What is the code license?

### ISSUE THREAD

**Issue by adam-p** [mmorearty/DispatchPtr#2]
I would like to use your code in a project (which is GPL, but maybe that's beside the point), but I think I first need to know the license your code is under. (IANAL, but I think the absence of a license means it can't be used at all -- or at least using it risks legal repercussions.)

**Comment by mmorearty** [comment]
Hi Adam,

You are welcome to use my code. I have not specified a license, but my code
is definitely not GPL; I don't want to impose those restrictions on it.

I tend to like licenses of the BSD variety. I suppose I could add a BSD
license if that would help.

**Comment by adam-p** [comment]
I don't need it to be GPL. I mostly just need it to be specified -- BSD is great. It just seems dangerous to use someone's code without them specifying the license it can be used under.

**Comment by mmorearty** [comment]
ok done
